//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int ParametroID { get; set; }
        public int ParametroTipoID { get; set; }
        public int Chave { get; set; }
        public string Valor { get; set; }
    
        public virtual ParametroTipo ParametroTipo { get; set; }
    }
}
