//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroTipo
    {
        public ParametroTipo()
        {
            this.Parametros = new HashSet<Parametros>();
        }
    
        public int ParametrosTipoID { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Parametros> Parametros { get; set; }
    }
}
